/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadResumeRouteImport } from './routes/upload-resume'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectLinkedinRouteImport } from './routes/connect-linkedin'
import { Route as ConnectGithubRouteImport } from './routes/connect-github'
import { Route as IndexRouteImport } from './routes/index'

const UploadResumeRoute = UploadResumeRouteImport.update({
  id: '/upload-resume',
  path: '/upload-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectLinkedinRoute = ConnectLinkedinRouteImport.update({
  id: '/connect-linkedin',
  path: '/connect-linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGithubRoute = ConnectGithubRouteImport.update({
  id: '/connect-github',
  path: '/connect-github',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-github': typeof ConnectGithubRoute
  '/connect-linkedin': typeof ConnectLinkedinRoute
  '/dashboard': typeof DashboardRoute
  '/upload-resume': typeof UploadResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-github': typeof ConnectGithubRoute
  '/connect-linkedin': typeof ConnectLinkedinRoute
  '/dashboard': typeof DashboardRoute
  '/upload-resume': typeof UploadResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-github': typeof ConnectGithubRoute
  '/connect-linkedin': typeof ConnectLinkedinRoute
  '/dashboard': typeof DashboardRoute
  '/upload-resume': typeof UploadResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-github'
    | '/connect-linkedin'
    | '/dashboard'
    | '/upload-resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-github'
    | '/connect-linkedin'
    | '/dashboard'
    | '/upload-resume'
  id:
    | '__root__'
    | '/'
    | '/connect-github'
    | '/connect-linkedin'
    | '/dashboard'
    | '/upload-resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectGithubRoute: typeof ConnectGithubRoute
  ConnectLinkedinRoute: typeof ConnectLinkedinRoute
  DashboardRoute: typeof DashboardRoute
  UploadResumeRoute: typeof UploadResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-resume': {
      id: '/upload-resume'
      path: '/upload-resume'
      fullPath: '/upload-resume'
      preLoaderRoute: typeof UploadResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-linkedin': {
      id: '/connect-linkedin'
      path: '/connect-linkedin'
      fullPath: '/connect-linkedin'
      preLoaderRoute: typeof ConnectLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-github': {
      id: '/connect-github'
      path: '/connect-github'
      fullPath: '/connect-github'
      preLoaderRoute: typeof ConnectGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectGithubRoute: ConnectGithubRoute,
  ConnectLinkedinRoute: ConnectLinkedinRoute,
  DashboardRoute: DashboardRoute,
  UploadResumeRoute: UploadResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
